### ISSUE TITLE
ActiveMQ tries to build before osdeps are resolved

### ISSUE THREAD

**Issue by wieset** [esa-prl/rover-package_set#3]
It seems that ActiveMQ is built by autoproj before the osdeps phase. This fails if the osdeps are not present on the system, even though they are defined in the manifest and osdeps file. Maybe this can be fixed in the autobuild commands?

**Comment by levingerdes** [comment]
Sure, I'll have a look. It had built so many times without any problems for the Docker images, so this is quite the surprise.

**Comment by wieset** [comment]
I tried to build it on the default Ubuntu image from Docker Hub which contains a quite reduced set of installed packages. Maybe in your image these osdeps (apr, autoconf, automake) were already installed?

**Comment by levingerdes** [comment]
I can confirm this behavior. As you can see in [the docker file](https://github.com/levingerdes/rock-docker/blob/master/Dockerfile#L22), `autoconf` is installed alongside the packages that are necessary for a rather minimal rock installation and [that this is only being installed for ActiveMQ](https://github.com/levingerdes/rock-docker/blob/master/Dockerfile#L31).

And as we can see here, we're definitely building ActiveMQ before installing osdeps, and this should be fixable in the autobuild script, just as you say.
```
checked out control/urdfdom_headers
checked out perception/viso2
patching perception/viso2: applying 2 patch(es) 
Configuring activeMQ package...
Configured activeMQ package
Building activeMQ package...
Built activeMQ package
Installing activeMQ package...
Commented out faulty line in activemq-cpp.pc
Installed activeMQ package
building initial autoproj import log, this may take a while
installing OS packages: autoconf-archive, avahi-daemon, castxml, cmake, freeglut3-dev, ...
```

**Comment by levingerdes** [comment]
It's now a bit tricky to test, because I can no longer bootstrap: https://github.com/esa-prl/buildconf/issues/1
